export const SITE_URL = 'https://canibringitnow.com';

export const INDEXABLE_STATIC_PATHS = [
  { path: '/', changeFrequency: 'weekly', priority: 1 },
  { path: '/check/', changeFrequency: 'weekly', priority: 0.9 },
  { path: '/search/', changeFrequency: 'weekly', priority: 0.8 },
  { path: '/rules/', changeFrequency: 'weekly', priority: 0.85 },
  { path: '/questions/', changeFrequency: 'weekly', priority: 0.82 },
  { path: '/categories/', changeFrequency: 'weekly', priority: 0.8 },
  { path: '/airlines/', changeFrequency: 'weekly', priority: 0.8 },
  { path: '/countries/', changeFrequency: 'weekly', priority: 0.8 },
  { path: '/travel-tools/', changeFrequency: 'weekly', priority: 0.76 },
  { path: '/travel-essentials/', changeFrequency: 'weekly', priority: 0.72 },
  { path: '/deals/', changeFrequency: 'weekly', priority: 0.7 },
  { path: '/about/', changeFrequency: 'monthly', priority: 0.7 },
  { path: '/contact/', changeFrequency: 'monthly', priority: 0.5 },
  { path: '/privacy/', changeFrequency: 'yearly', priority: 0.3 },
  { path: '/terms/', changeFrequency: 'yearly', priority: 0.3 },
  { path: '/disclaimer/', changeFrequency: 'yearly', priority: 0.5 },
] as const;

export const INTERNAL_NOINDEX_PATHS = [
  '/adsense-layout/',
  '/affiliate-components/',
  '/ai-content-factory/',
  '/ai-marketing-seeds/',
  '/analytics-intelligence/',
  '/analytics-plan/',
  '/analytics-setup/',
  '/atlas-audit/',
  '/authority-clusters/',
  '/backlink-outreach-hub/',
  '/content-expansion-queue/',
  '/content-qa-checklist/',
  '/ctr-booster/',
  '/editorial-calendar/',
  '/g10-complete/',
  '/growth-command-center/',
  '/growth-command-centre/',
  '/growth-engine/',
  '/high-intent-page-factory/',
  '/home-2/',
  '/indexable-pages-map/',
  '/indexing-control/',
  '/internal-link-optimizer/',
  '/internal-links/',
  '/launch-control/',
  '/launch-readiness/',
  '/manual-work-reducer/',
  '/newsletter-starter/',
  '/next-30-days/',
  '/page-refresh-queue/',
  '/pinterest-pin-factory/',
  '/production-dashboard/',
  '/qa/',
  '/quality-audit/',
  '/revenue-intelligence/',
  '/revenue-launch/',
  '/revenue-readiness-score/',
  '/revenue-safe-zones/',
  '/search-console-action-plan/',
  '/seo-health-monitor/',
  '/seo-network/',
  '/seo-scale/',
  '/social-distribution-plan/',
  '/social-export-studio/',
  '/traffic-command/',
  '/traffic-magnets/',
  '/utm-campaign-builder/',
  '/v2-foundation/',
  '/v2-travel-brain/',
  '/v3-core/',
  '/video-script-factory/',
  '/visitor-retention-engine/',
  '/orbit/',
  '/orbit-release-2/',
  '/orbit-release-3/',
  '/orbit-release-4/',
  '/orbit-release-6/',
  '/orbit-release-7/',
  '/orbit-sitemap/',
  '/orbit-international/',
  '/growth/',
  '/growth8/',
  '/growth9/',
  '/intelligence/',
  '/launch/',
  '/marketing/',
  '/orbit2/',
] as const;

export function absoluteUrl(path: string): string {
  return `${SITE_URL}${path}`;
}
