import type { Metadata } from 'next';
import { notFound } from 'next/navigation';
import { ArrowRight, BookOpenCheck, Calendar, CheckCircle2, Clock, ExternalLink, ShieldCheck } from 'lucide-react';
import FaqBlock from '@/components/seo/FaqBlock';
import GuideCard from '@/components/guides/GuideCard';
import { getKnowledgeGuide, knowledgeGuides } from '@/data/knowledgeGuides';
import { rules } from '@/data/rules';

export function generateStaticParams() { return knowledgeGuides.map((guide) => ({ slug: guide.slug })); }
export function generateMetadata({ params }: { params: { slug: string } }): Metadata {
  const guide = getKnowledgeGuide(params.slug);
  if (!guide) return { title: 'Guide not found' };
  return { title: guide.title, description: guide.description, alternates: { canonical: `/guides/${guide.slug}/` }, openGraph: { title: guide.title, description: guide.description, type: 'article', url: `/guides/${guide.slug}/` } };
}

export default function GuidePage({ params }: { params: { slug: string } }) {
  const guide = getKnowledgeGuide(params.slug); if (!guide) notFound();
  const relatedRules = rules.filter((rule) => guide.relatedRuleTerms.some((term) => [rule.item, rule.category, ...rule.tags].join(' ').toLowerCase().includes(term.toLowerCase()))).slice(0, 8);
  const relatedGuides = knowledgeGuides.filter((item) => item.slug !== guide.slug && item.tags.some((tag) => guide.tags.includes(tag))).slice(0, 3);
  const articleSchema = { '@context': 'https://schema.org', '@type': 'Article', headline: guide.title, description: guide.description, dateModified: guide.updated, datePublished: guide.updated, author: { '@type': 'Organization', name: 'Can I Bring It Now' }, publisher: { '@type': 'Organization', name: 'Can I Bring It Now', url: 'https://canibringitnow.com' }, mainEntityOfPage: `https://canibringitnow.com/guides/${guide.slug}/` };
  const breadcrumbSchema = { '@context': 'https://schema.org', '@type': 'BreadcrumbList', itemListElement: [{ '@type': 'ListItem', position: 1, name: 'Home', item: 'https://canibringitnow.com/' }, { '@type': 'ListItem', position: 2, name: 'Guides', item: 'https://canibringitnow.com/guides/' }, { '@type': 'ListItem', position: 3, name: guide.shortTitle, item: `https://canibringitnow.com/guides/${guide.slug}/` }] };
  return <main className="min-h-screen bg-slate-50"><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(articleSchema) }} /><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(breadcrumbSchema) }} />
    <section className="bg-gradient-to-br from-brand-50 via-white to-sky-50"><div className="mx-auto max-w-5xl px-5 py-12 md:px-8 md:py-16"><a href="/guides/" className="font-bold text-brand-600">← Travel Knowledge Centre</a><p className="mt-8 font-black uppercase tracking-wide text-brand-600">{guide.category}</p><h1 className="mt-3 text-4xl font-black tracking-tight text-slate-950 md:text-6xl">{guide.title}</h1><p className="mt-6 max-w-4xl text-lg leading-8 text-slate-600">{guide.description}</p><div className="mt-6 flex flex-wrap gap-3 text-sm font-semibold text-slate-600"><span className="inline-flex items-center gap-2 rounded-full bg-white px-4 py-2 ring-1 ring-slate-200"><Clock className="h-4 w-4" />{guide.readingMinutes} min read</span><span className="inline-flex items-center gap-2 rounded-full bg-white px-4 py-2 ring-1 ring-slate-200"><Calendar className="h-4 w-4" />Updated {guide.updated}</span><span className="inline-flex items-center gap-2 rounded-full bg-white px-4 py-2 ring-1 ring-slate-200"><ShieldCheck className="h-4 w-4" />For {guide.audience}</span></div></div></section>
    <div className="mx-auto grid max-w-5xl gap-8 px-5 py-10 md:px-8"><section className="rounded-3xl bg-slate-950 p-6 text-white md:p-8"><div className="flex items-center gap-3"><BookOpenCheck className="h-6 w-6 text-sky-300" /><h2 className="text-2xl font-black">Key takeaways</h2></div><ul className="mt-5 grid gap-3 md:grid-cols-2">{guide.keyTakeaways.map((item) => <li key={item} className="flex gap-3 rounded-2xl bg-white/10 p-4 leading-7"><CheckCircle2 className="mt-1 h-5 w-5 shrink-0 text-green-300" />{item}</li>)}</ul></section>
      {guide.sections.map((section) => <section key={section.heading} className="rounded-3xl bg-white p-6 shadow-soft ring-1 ring-slate-200 md:p-8"><h2 className="text-2xl font-black text-slate-950">{section.heading}</h2>{section.paragraphs.map((paragraph) => <p key={paragraph} className="mt-4 leading-8 text-slate-600">{paragraph}</p>)}{section.bullets && <ul className="mt-5 list-disc space-y-2 pl-6 leading-7 text-slate-600">{section.bullets.map((bullet) => <li key={bullet}>{bullet}</li>)}</ul>}</section>)}
      <section className="rounded-3xl bg-white p-6 ring-1 ring-slate-200 md:p-8"><div className="flex items-center gap-3"><ExternalLink className="h-6 w-6 text-brand-600" /><h2 className="text-2xl font-black text-slate-950">Official checks before travel</h2></div><div className="mt-5 grid gap-4 md:grid-cols-2">{guide.officialChecks.map((item) => <div key={item.label} className="rounded-2xl bg-slate-50 p-5 ring-1 ring-slate-200"><h3 className="font-black text-slate-950">{item.label}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{item.description}</p></div>)}</div></section>
      <FaqBlock items={guide.faqs} />
      {relatedRules.length > 0 && <section className="rounded-3xl bg-white p-6 ring-1 ring-slate-200 md:p-8"><p className="font-black uppercase tracking-wide text-brand-600">Related checks</p><h2 className="mt-2 text-2xl font-black text-slate-950">Apply this guidance to specific items</h2><div className="mt-5 grid gap-3 md:grid-cols-2">{relatedRules.map((rule) => <a key={rule.slug} href={`/rules/${rule.slug}/`} className="rounded-2xl bg-slate-50 p-4 ring-1 ring-slate-200 hover:bg-brand-50"><p className="font-black text-slate-950">{rule.item}</p><p className="mt-2 line-clamp-2 text-sm leading-6 text-slate-600">{rule.shortAnswer}</p><span className="mt-3 inline-flex items-center gap-2 text-sm font-black text-brand-600">Open rule <ArrowRight className="h-4 w-4" /></span></a>)}</div></section>}
      {relatedGuides.length > 0 && <section><h2 className="text-2xl font-black text-slate-950">Continue learning</h2><div className="mt-5 grid gap-4 md:grid-cols-3">{relatedGuides.map((item) => <GuideCard key={item.slug} guide={item} />)}</div></section>}
    </div></main>;
}
