import Orbit2Hero from '@/components/orbit2/Orbit2Hero';
const examples = [
  { old: 'Power bank on Virgin Atlantic', newTitle: 'Can I Take a Power Bank on Virgin Atlantic? Cabin & Checked Rules', reason: 'Question-led title improves search intent match.' },
  { old: 'Medication on a plane', newTitle: 'Can I Take Medication on a Plane? Cabin, Checked & Prescription Rules', reason: 'Adds high-intent terms: medication, plane, cabin, checked, prescription.' },
  { old: 'Baby milk on a plane', newTitle: 'Can I Take Baby Milk on a Plane? Formula & Airport Security Rules', reason: 'Targets baby milk, formula and airport security.' },
  { old: 'Liquids TSA', newTitle: 'Can I Take Liquids in Hand Luggage? 100ml Airport Security Rules', reason: 'Adds hand luggage and 100ml terms.' },
];
export const metadata = { title: 'CTR Booster | Can I Bring It Now', description: 'Title, meta description and snippet improvement plan for higher Google click-through rate.', alternates: { canonical: '/ctr-booster/' } };
export default function CtrBoosterPage() { return <main className="min-h-screen bg-slate-50 pb-24 md:pb-0"><section className="bg-gradient-to-br from-brand-50 via-white to-sky-50"><div className="mx-auto max-w-6xl px-5 py-10 md:px-8"><a href="/orbit-release-2/" className="text-sm font-semibold text-brand-600">← ORBIT Release 2</a><Orbit2Hero eyebrow="CTR Booster" title="Make Google searchers click your result" description="When Search Console shows impressions but low CTR, improve the title, meta description and first-answer block before creating more pages." /><section className="mt-8 rounded-3xl bg-white p-6 shadow-soft ring-1 ring-slate-200"><p className="font-bold text-brand-600">Title improvements</p><h2 className="mt-2 text-2xl font-black text-slate-950">Before and after examples</h2><div className="mt-5 grid gap-3">{examples.map((example) => <article key={example.old} className="rounded-2xl bg-slate-50 p-4 ring-1 ring-slate-200"><p className="text-sm text-slate-500">Old: {example.old}</p><p className="mt-2 text-lg font-black text-slate-950">New: {example.newTitle}</p><p className="mt-2 text-sm leading-6 text-slate-600">{example.reason}</p></article>)}</div></section></div></section></main>; }
