import type { Metadata } from 'next';
import { ArrowRight, BarChart3, Download, Layers3, ShieldCheck } from 'lucide-react';
import { categories, rules } from '@/data/rules';
import { buildClusterSummary } from '@/lib/build26Authority';

export const metadata: Metadata = { title: 'Travel Rules Authority Centre | Can I Bring It Now', description: 'Explore structured travel-rule clusters, methodology and a downloadable snapshot of the Can I Bring It Now rules database.', alternates: { canonical: '/travel-authority/' } };

export default function TravelAuthorityPage() {
  const clusters = buildClusterSummary(rules);
  const warnings = rules.filter((rule) => Boolean(rule.warning)).length;
  const restricted = rules.filter((rule) => rule.cabin === 'Restricted' || rule.checked === 'Restricted').length;
  return <main className="min-h-screen bg-slate-50"><section className="bg-slate-950 text-white"><div className="mx-auto max-w-6xl px-5 py-16 md:px-8"><p className="font-bold text-sky-300">Build 26 authority centre</p><h1 className="mt-3 text-4xl font-black md:text-6xl">Travel rules organised into useful topic clusters.</h1><p className="mt-5 max-w-3xl text-lg leading-8 text-slate-300">Browse the structured rules database by topic, understand the methodology and download the current research snapshot for reference.</p><a href="/downloads/canibringitnow-travel-rules-snapshot.csv" className="mt-7 inline-flex items-center gap-2 rounded-2xl bg-white px-5 py-3 font-bold text-slate-950"><Download className="h-4 w-4" />Download CSV snapshot</a></div></section>
  <section className="mx-auto max-w-6xl px-5 py-12 md:px-8"><div className="grid gap-4 md:grid-cols-4">{[[rules.length,'Structured rules'],[categories.length,'Categories'],[warnings,'Rules with warnings'],[restricted,'Restricted decisions']].map(([value,label]) => <div key={label} className="rounded-3xl bg-white p-6 ring-1 ring-slate-200"><p className="text-4xl font-black text-slate-950">{value}</p><p className="mt-2 text-sm font-semibold text-slate-600">{label}</p></div>)}</div>
  <div className="mt-10 rounded-3xl bg-white p-7 ring-1 ring-slate-200"><div className="flex items-center gap-3"><Layers3 className="h-7 w-7 text-brand-600"/><h2 className="text-2xl font-black text-slate-950">Topic clusters</h2></div><div className="mt-6 grid gap-3 md:grid-cols-2">{clusters.map((cluster) => <a key={cluster.category} href={`/categories/${cluster.category.toLowerCase().replace(/&/g,'and').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')}/`} className="flex items-center justify-between rounded-2xl bg-slate-50 p-4 ring-1 ring-slate-200"><div><p className="font-black text-slate-950">{cluster.category}</p><p className="text-sm text-slate-600">{cluster.count} structured rule records</p></div><ArrowRight className="h-5 w-5 text-brand-600"/></a>)}</div></div>
  <div className="mt-8 grid gap-5 md:grid-cols-2"><div className="rounded-3xl bg-white p-7 ring-1 ring-slate-200"><BarChart3 className="h-7 w-7 text-brand-600"/><h2 className="mt-4 text-2xl font-black">Methodology</h2><p className="mt-3 leading-7 text-slate-600">Counts are calculated from the published rule records at build time. Each record includes cabin and checked-baggage classifications, restrictions, practical tips, a review date and a source note.</p></div><div className="rounded-3xl bg-white p-7 ring-1 ring-slate-200"><ShieldCheck className="h-7 w-7 text-brand-600"/><h2 className="mt-4 text-2xl font-black">Important limitation</h2><p className="mt-3 leading-7 text-slate-600">This dataset is general travel guidance, not an official regulatory database. Rules can vary by airline, airport, route and destination. Always verify important decisions with official sources.</p></div></div></section></main>;
}
